@switch($random)
  @case(5)
    <p>大ラッキーの１日です！</p>
    @break
  @case(4)
    <p>ちょっぴりいいことがあるかも？</p>
    @break
  @case(3)
    <p>フツーの１日です</p>
    @break
  @case(2)
    <p>今日は静かに過ごしましょう...</p>
    @break
  @default
    <p>umm...</p>
@endswitch
